language: node_js
node_js:
    - '0.12'

before_install:
    - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
    - npm install -g npm@2.12

after_success:
    - ./node_modules/.bin/jscoverage translit.js translit-cov.js
    - NPM_COV=1 ./node_modules/.bin/mocha test -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
